name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Zip Python script and dependencies
      run: |
        mkdir package
        cp -r main.py package/
        cp -r requirements.txt package/
        #cp -r venv package/
        zip -r main.zip package
      
    - name: Install AWS CLI
      run: |
        apt-get install -y python3-pip
        pip3 install awscli
        
        
#     - name: Install AWS CLI
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#       run: |
#         python -m pip install awscli

    - name: Install and configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2


    - name: Deploy to S3
      run: aws s3 cp main.zip s3://lambda-functions-cm443/main.zip


# name: Deploy Lambda function to S3

# on:
#   push:
#     branches:
#       - main

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   S3_BUCKET: lambda-functions-cm443
#   LAMBDA_FUNCTION_NAME: my-lambda-function
#   GITHUB_WORKSPACE: cm-443/lambda-test/

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
    
#     - name: Setup Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
    
#     - name: Package Lambda function
#       run: |
#         cd 'cm-443/lambda-test'
#         zip -r9 ${GITHUB_WORKSPACE}/$LAMBDA_FUNCTION_NAME.zip .
    
#     - name: Deploy to S3
#       run: |
#         aws s3 cp ${GITHUB_WORKSPACE}/$LAMBDA_FUNCTION_NAME.zip s3://$S3_BUCKET/
