name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    # - name: Zip Python script and dependencies
    #   run: |
    #     mkdir package
    #     cp -r main.py package/
    #     cp -r requirements.txt package/
    #     #cp -r venv package/
    #     zip -r main.zip package
        
    - name: Zip Python script and dependencies
      run: |
        pip freeze > requirements.txt
        pip install -r requirements.txt
        mkdir package
        cp -r main.py package/
        cp -r requirements.txt package/
        zip -r main.zip package        
        

#     - name: Zip Python script and dependencies
#       run: |
#         pip freeze > requirements.txt
#         python -m venv venv
#         source venv/bin/activate
#         pip install --no-compile -r requirements.txt
#         cp -r main.py venv/
#         zip -r main.zip venv    
      
    - name: Install AWS CLI
      run: sudo apt-get install -y awscli
    - name: Configure AWS credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-east-2
    - name: Upload file to S3
      run: aws s3 cp main.zip s3://lambda-functions-cm443/main.zip






