name: Deploy to S3


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Zip Python script and dependencies
      run: |
        mkdir package
        cp -r main.py package/
        cp -r requirements.txt package/
        #cp -r venv package/
        zip -r main.zip package
        
#     - name: Configure AWS credentials
#       run: |
#         mkdir ~/.aws
#         echo "[default]\naws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
      
#     - name: Upload file to S3
#       run: |
#         pip install boto3
#         python -c "import boto3; s3 = boto3.client('s3'); s3.upload_file('main.zip', 'lambda-functions-cm443', 'main.zip')"


#     - name: Deploy to S3
#       run: aws s3 cp main.zip s3://lambda-functions-cm443/main.zip
      
    - name: Install AWS CLI
      run: sudo apt-get install -y awscli
    - name: Configure AWS credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-east-2
    - name: Upload file to S3
      run: aws s3 cp main.zip s3://lambda-functions-cm443/main.zip

#aws s3 cp main.zip s3://lambda-functions-cm443/main.zip




# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   S3_BUCKET: lambda-functions-cm443
#   LAMBDA_FUNCTION_NAME: my-lambda-function
#   GITHUB_WORKSPACE: cm-443/lambda-test/



