name: Deploy Lambda function to S3

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET: lambda-functions-cm443
  LAMBDA_FUNCTION_NAME: my-lambda-function
  GITHUB_WORKSPACE: cm-443/lambda-test/

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Package Lambda function
      run: |
        cd cm-443/lambda-test
        zip -r9 ${GITHUB_WORKSPACE}/$LAMBDA_FUNCTION_NAME.zip .
    
    - name: Deploy to S3
      run: |
        aws s3 cp ${GITHUB_WORKSPACE}/$LAMBDA_FUNCTION_NAME.zip s3://$S3_BUCKET/